"""Type stubs for treelite_rs.frontend (PEP 561, D-10)."""

from __future__ import annotations

import pathlib
from typing import Union

from .model import Model

def load_xgboost_model(
    filename: Union[str, pathlib.Path],
    *,
    format_choice: str = ...,
) -> Model: ...
def load_xgboost_model_legacy_binary(
    filename: Union[str, pathlib.Path],
) -> Model: ...
def load_lightgbm_model(filename: Union[str, pathlib.Path]) -> Model: ...

# Raw compiled str/bytes entry points (Rust seam).
def load_xgboost_json_str(json: str) -> Model: ...
def load_xgboost_ubjson_bytes(data: bytes) -> Model: ...
def load_xgboost_legacy_bytes(data: bytes) -> Model: ...
def load_lightgbm_str(text: str) -> Model: ...
def detect_xgboost_format_bytes(data: bytes) -> str: ...
